# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/family.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data/family.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x64\x61ta/family.proto\"\xb0\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12*\n\x0crelationship\x18\x04 \x01(\x0e\x32\x14.Person.Relationship\"_\n\x0cRelationship\x12\n\n\x06\x46\x41THER\x10\x00\x12\n\n\x06MOTHER\x10\x01\x12\x07\n\x03SON\x10\x02\x12\x0c\n\x08\x44\x41UGHTER\x10\x03\x12\x0f\n\x0bGRANDFATHER\x10\x04\x12\x0f\n\x0bGRANDMOTHER\x10\x05\"!\n\x06\x46\x61mily\x12\x17\n\x06person\x18\x01 \x03(\x0b\x32\x07.Personb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PERSON_RELATIONSHIP = _descriptor.EnumDescriptor(
  name='Relationship',
  full_name='Person.Relationship',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FATHER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTHER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SON', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAUGHTER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRANDFATHER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRANDMOTHER', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=103,
  serialized_end=198,
)
_sym_db.RegisterEnumDescriptor(_PERSON_RELATIONSHIP)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='Person.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relationship', full_name='Person.relationship', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERSON_RELATIONSHIP,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=198,
)


_FAMILY = _descriptor.Descriptor(
  name='Family',
  full_name='Family',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='Family.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=233,
)

_PERSON.fields_by_name['relationship'].enum_type = _PERSON_RELATIONSHIP
_PERSON_RELATIONSHIP.containing_type = _PERSON
_FAMILY.fields_by_name['person'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Family'] = _FAMILY

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'data.family_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  ))
_sym_db.RegisterMessage(Person)

Family = _reflection.GeneratedProtocolMessageType('Family', (_message.Message,), dict(
  DESCRIPTOR = _FAMILY,
  __module__ = 'data.family_pb2'
  # @@protoc_insertion_point(class_scope:Family)
  ))
_sym_db.RegisterMessage(Family)


# @@protoc_insertion_point(module_scope)
